version: "3"

services: 
  postgres:
    image: postgres:${POSTGRES_VERSION}
    container_name: compose_cl_postgres
    ports:
      - 5432:5432
    env_file: 
      - .env
    volumes: 
      - db-data:/var/lib/postgresql/data

  chainlink:
    build: .
    container_name: compose_chainlink
    #user: chainlink:14933
    env_file:
      - .env
    command: local node -p /home/chainlink/.password -a /home/chainlink/.api
    #command: "-f /dev/null"
    #entrypoint: /usr/bin/tail
    #tty: true
    #restart: on-failure
    ports: 
      - 6688:6688
    links:
      - postgres
    depends_on: 
      - postgres
    volumes:
      - ./chainlink_data:/home/chainlink

volumes: 
  db-data:
