version: "3"

services: 
  postgres:
    image: postgres:${POSTGRES_VERSION}
    container_name: postgres
    ports:
      - 5432:5432
    env_file: 
      - .env
    volumes: 
      - db-data:/var/lib/postgresql/data

  chainlink:
    image: 'smartcontract/chainlink:2.5.0'
    platform: linux/x86_64
    container_name: chainlink-mumbai
    volumes:
      - ./config:/chainlink
    stdin_open: true
    tty: true
    ports:
      - '6688:6688'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    command: 'node -config /chainlink/config.toml -secrets /chainlink/secrets.toml start -a /chainlink/.api -p /chainlink/.password'
    depends_on:
      - postgres

volumes: 
  db-data:
